### ISSUE TITLE
Can't build version 1.0.0

### ISSUE THREAD

**Issue by richardwhitehead** [nroduit/weasis-dicom-tools#1]
I've been trying to compile the version 1.0 source code but it doesn't seem to be compatible with the last released build (3.3.7) of dcm4che3 which it relies on.  I also tried the current master branch of dcm4che3 but I couldn't get that to build either.
Please could you clarify which version of dcm4che3 it builds against.

**Comment by nroduit** [comment]
The dcm4che version is defined in [pom.xml](https://github.com/nroduit/weasis-dicom-tools/blob/master/pom.xml)
