### ISSUE TITLE
Publish new versions on maven central

### ISSUE THREAD

**Issue by vkorchik** [nroduit/weasis-dicom-tools#14]
Hi guys,

why do not you publish the jars on maven central? The only version there is 5.22.4. Is that a problem to publish on maven?

maven.scijava.org is pretty often dead, and I am not able to pull the jars. Central repo on the other hand is much more stable and resilent.

Cherrs,
Vlad

**Comment by nroduit** [comment]
I maintain only [this GitHub maven repo](https://github.com/nroduit/mvn-repo/tree/master/org/weasis/weasis-dicom-tools) and I am not responsible for other deployments.

You should add the repositories config:
```xml
  <repositories>
    <repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <repository>
      <id>mvn-repo-master</id>
      <url>https://raw.github.com/nroduit/mvn-repo/master/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>www.dcm4che.org</id>
      <name>dcm4che Repository</name>
      <url>http://maven.dcm4che.org</url>
    </repository>
  </repositories>
```

**Comment by vkorchik** [comment]
Hello @nroduit ,

last time it somehow started work for me, but yesterday I was trying to update to version 5.23.3 and got the same issue.

I am not a PRO of deployment stuff. Could you tell me how can weasis-dicom-tools be deployed to scijava repo? 
I want to see there version 5.23.3 but the last one there is 5.23.2. One the other hand dcm4che removed its 5.23.2 versions from maven and scijava. So currently as you see I have a problem.

Appreciate your help a lot :)

Cheers

**Comment by nroduit** [comment]
You should use the official repository mentioned above. I will not spend time on other repositories.

**Comment by nroduit** [comment]
Currently dcm4che is down: https://groups.google.com/g/dcm4che/c/S9l7CjSaOoc
