### ISSUE TITLE
CLIUtils out of date

### ISSUE THREAD

**Issue by ncioj10** [nroduit/weasis-dicom-tools#15]
The version of CLIUtils seems to be out of date. This creates a conflict because I'm trying to use the `weasis-dicom-tools:5.26.0` in combination with Dcm2Jpg `org.dcm4che.tool:dcm4che-tool-dcm2jpg:5.26.0`, which tries to call `public static CommandLine parseComandLine(String[] args, Options opts, rb2, Class<?> clazz)`, but it doesn't exist.
What's the best way to convert DICOM to JPG in this configuration?

**Comment by nroduit** [comment]
The APIs in weasis-dicom-tools are designed to avoid using the script commands in dcm4che.

I have updated the [readme page](https://github.com/nroduit/weasis-dicom-tools/) to explain the use of the image transformation APIs. The APIs offer more functionality than in dcm4che image conversion types (e.g. allows to preserve 16-bit in a png image).

See also the [test classes](https://github.com/nroduit/weasis-dicom-tools/tree/master/src/test/java/org/dcm4che3/img).
