### ISSUE TITLE
can't read Chinese words

### ISSUE THREAD

**Issue by Fearself** [nroduit/weasis-dicom-tools#24]
in CFindNetTest can't read Chinese words "(0010,0010) PN [] PatientName" , it's null , HELP!

**Comment by nroduit** [comment]
More information is needed (context, system, Java version, log errors...)

**Comment by Fearself** [comment]
> More information is needed (context, system, Java version, log errors...)
Windows System(Windows11)
weasis-dicom-tools(5.25.2)
java version(1.8)
in use “class CFindNetTest“ and try to read some Tags but found can't read chinese words ,its null , like this 
![image](https://user-images.githubusercontent.com/32427374/228717026-52e19285-710a-4104-ad1f-6c6f537d9710.png)
![image](https://user-images.githubusercontent.com/32427374/228717192-b2e0fd51-b117-4f3a-ad5b-a5ef10ec03fe.png)
Thank for your reply

**Comment by nroduit** [comment]
The problem is in the response side of the server which has an ISO_IR_100 encoding. It should be ISO_IR 192.

**Comment by nroduit** [comment]
If you specify the charset in the query, it doesn't mean that the response must be in the same encoding, see this [post](https://stackoverflow.com/questions/68497012/can-we-set-multiple-dcm-specificcharacterset-while-importing-records-using-dicom).

**Comment by Fearself** [comment]
my server is  “ISO_IR 192“ encoding
![image](https://user-images.githubusercontent.com/32427374/229017468-1d68a2ca-03a8-4097-8894-ac56ca0857a7.png)
but i read it's "ISO_IR_100",i have no idea
![image](https://user-images.githubusercontent.com/32427374/229017538-d8f6548b-615b-4bcb-9465-888a39bb753a.png)
i debug in  class FindSCU ,i try to set "Tag.SpecificCharacterSet" but it's not work, how i can change the encoding
![image](https://user-images.githubusercontent.com/32427374/229017773-391cc72b-4789-4fd2-a1ab-6f2a303a9a5f.png)

**Comment by nroduit** [comment]
You can try to add `new DicomParam(Tag.SpecificCharacterSet, "ISO_IR 192"),` in the query but as mentioned above this is the encoding only for the query part.

The file is stored with the encoding ISO_IR 192 on your server but the DICOM response of C-FIND is ISO_IR_100. This problem can only be solved in Orthanc.
