### ISSUE TITLE
Cannot integrate tools to Weasis 

### ISSUE THREAD

**Issue by sMoKeSz** [nroduit/weasis-dicom-tools#27]
Hi, I tried to add this tools pack in Weasis, after building and so one, but there is no chance.
I am missing something ? I tried with plugins tutorial from the website (https://weasis.org/en/basics/customize/build-plugins/#install-plug-ins) but cannot locate the conf file for plugins and the plugins folder.

Thank you.

**Comment by nroduit** [comment]
If you want to add a plugin, follow the instructions on this [page](https://weasis.org/en/getting-started/guidelines/).

Please note that the documentation for building plugins is not up to date, since version 4.2.0 properties files have been replaced by json files.
