### ISSUE TITLE
CGet.STORAGE_SOP needs to be modifieable

### ISSUE THREAD

**Issue by richardwhitehead** [nroduit/weasis-dicom-tools#5]
There is no way to extend this array so that CGet can be used for other (less common) data classes.
Also, for those only interested in one type of data, they still have to accept all types which makes the DICOM Conformance Statement look bizarre.

I'm using Weasis tools v1.0.2.  Note that ours is a medical product so we want to use a formally released version.

**Comment by nroduit** [comment]
This has be done is the [latest commit](https://github.com/nroduit/weasis-dicom-tools/commit/b93f3e43fe712bf15fd8a28a9a04c1d911a65956). As the negotiation with CGET is very complex, the best solution is to customize the configuration file. However, I've added more sop classes in the [default file](https://github.com/nroduit/weasis-dicom-tools/blob/master/src/main/resources/org/dcm4che3/tool/getscu/store-tcs.properties)

I also fix some issues with wrong success status and improve the returning message.

**Comment by nroduit** [comment]
The version 1.0.3 will be released very soon. Let me know if you see other issues.

**Comment by richardwhitehead** [comment]
Thanks very much for your support, and for the excellent toolkit. 

 

Richard
