### ISSUE TITLE
CMove.process Passing SOPInstanceUID parameters,obtain the result error

### ISSUE THREAD

**Issue by chendd1016** [nroduit/weasis-dicom-tools#6]
Hello, thank you very much to use your tools version 1.2.0. I found some problems in the use of CMove.process(), need your help.
When I passed StudyInstanceUID parameters, the results correctly;
When I passed SOPInstanceUID parameters, the result error.
the code is as follows:

`DicomParam[] params =
            { new DicomParam(Tag.SOPInstanceUID, "1.2.826.0.3.93.95.201705090910533.6") };
        DicomNode calling = new DicomNode("WEASIS-SCU");
        DicomNode called = new DicomNode("TRPACS", "192.168.3.120", 11246);
        DicomState state = CMove.process(calling, called, "DWV-SCP", progress, params);`

**Comment by nroduit** [comment]
As the default c-move model is a study model, you need to add some more options.
I added in the [test class](https://github.com/nroduit/weasis-dicom-tools/blob/master/src/test/java/org/weasis/dicom/CMoveNetTest.java) how to move a series or an image.


```java   
DicomParam[] params = { new DicomParam(Tag.QueryRetrieveLevel, "IMAGE"),
    new DicomParam(Tag.SOPInstanceUID, "1.2.840.113543.6.6.3.4.637463244096141531813342472862196132286") };
DicomNode calling = new DicomNode("WEASIS-SCU");
DicomNode called = new DicomNode("DCM4CHEE", "localhost", 11112);
AdvancedParams options = new AdvancedParams();
options.getQueryOptions().add(QueryOption.RELATIONAL); // Required for QueryRetrieveLevel other than study
DicomState state = CMove.process(options, calling, called, "WEASIS-SCU", progress, params);
```

**Comment by chendd1016** [comment]
Thanks very much for your support.
